import Head from "next/head";
import TodoForm from "./../src/components/TodoForm";

export default function Home() {
  return (
    <div className="container mx-auto flex justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center">
        <TodoForm />
      </div>
    </div>
  );
}
